# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Handle.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 557)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_6)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_5)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.label_7)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 24))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionTool_Support_Mack_Ding = QtWidgets.QAction(MainWindow)
        self.actionTool_Support_Mack_Ding.setObjectName("actionTool_Support_Mack_Ding")
        self.actionVersion_1_0 = QtWidgets.QAction(MainWindow)
        self.actionVersion_1_0.setObjectName("actionVersion_1_0")
        self.actionIntroduction_Enter_the_account_Login_Name_password_Email_and_click_Register_Complete_PP_Environment_ACA_account_registration = QtWidgets.QAction(MainWindow)
        self.actionIntroduction_Enter_the_account_Login_Name_password_Email_and_click_Register_Complete_PP_Environment_ACA_account_registration.setObjectName("actionIntroduction_Enter_the_account_Login_Name_password_Email_and_click_Register_Complete_PP_Environment_ACA_account_registration")
        self.menuHelp.addAction(self.actionTool_Support_Mack_Ding)
        self.menuHelp.addAction(self.actionVersion_1_0)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Register_PP_ACA"))
        self.label_2.setText(_translate("MainWindow", "Introduction："))
        self.label_6.setText(_translate("MainWindow", "1.Enter the account Login_Name, password, Email and click Register. "))
        self.label_5.setText(_translate("MainWindow", "2.Complete PP Environment ACA account registration."))
        self.label.setText(_translate("MainWindow", "Login_name"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.label_4.setText(_translate("MainWindow", "Email"))
        self.pushButton.setText(_translate("MainWindow", "Register"))
        self.label_7.setText(_translate("MainWindow", "Disclaimer: This tool is only for QIMA internal staff use."))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionTool_Support_Mack_Ding.setText(_translate("MainWindow", "Author: Mack Ding"))
        self.actionVersion_1_0.setText(_translate("MainWindow", "Version : 1.0"))
        self.actionIntroduction_Enter_the_account_Login_Name_password_Email_and_click_Register_Complete_PP_Environment_ACA_account_registration.setText(_translate("MainWindow", "Introduction：Enter the account Login_Name, password, Email and click Register. Complete PP Environment ACA account registration."))

